name: ci-cd-fauna

on:
  push:
    branches:
      - fauna

env:
  PREVIEW: true
  HUGO_VERSION: '0.74.1'
  NODE_VERSION: '12.14.0'
  NETLIFY_SITE_ID: '6cd6f28a-2d4d-4f85-97f7-5e2bc4e076ed'
  NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN_WEBSITE }}

jobs:
  build-and-deploy:
    name: Build & deploy
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: ${{ env.NODE_VERSION }}
      if: success()
    - name: Install dependencies
      run: |
        npm ci
        npm i -g gulp-cli postcss-cli@7 autoprefixer@9 netlify-cli
        cd functions
        npm ci
      if: success()
    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: ${{ env.HUGO_VERSION }}
        extended: true
      if: success()
    - name: Build site
      run: npm run build-fauna
      if: success()
    - name: Deploy site
      run: npm run deploy
      if: success()
